### ISSUE TITLE
Bot crashes upon any and all DMs

### ISSUE THREAD

**Issue by Hargers** [TFAGaming/DiscordJS-V14-Bot-Template#18]
_events/Guild/messageCreate.js_ initiates the constant variable 'prefix' before checking to see if the message was sent in a guild text channel. Because there is no `guild.id` object for direct messages, this crashes the bot.

**Comment by TFAGaming** [comment]
fixed, thanks for telling me the error.

**Comment by theabraxas** [comment]
Is there a way to have this handle DMs instead of just ignoring them? I'd love for the user to be able to talk directly. I know I can remove the ` if (message.channel.type !== 0) return;` which will cause it to crash (because the guild references don't exist). 

Is there any easy way to modify this? maybe another client.on('messageCreate'...) block where `message.channel.type == 0` and then have it import a new folder of commands or something?
